### ISSUE TITLE
Create a Logo

### ISSUE THREAD

**Issue by chrisjtraver** [ssanchez/friday-challenge.com#17]
We need a beautiful logo to replace the template provided one.

**Comment by zuurw** [comment]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!

**Comment by danieluhl** [comment]
@zuurw That would be awesome! The spirit of the project is helping others both learn and teach by doing weekly challenges. Do you know the typical sizes and dimensions websites need? I'm initially thinking a large landscape one for the homepage, header, or stickers. A large square version that may just be the initials FC or something like that. And a tiny one for the favicon.

**Comment by zuurw** [comment]
Hi @danieluhl, I see that you have alredy a idea for the logo, so I will start to design the logo and the favicon.
For the website can you give memore informations about what you want? can you give me something to get inspired?
Greetings

**Comment by danieluhl** [comment]
Most of the current challenges are in JavaScript so taking inspiration from the yellow JS logo or the react logo would make sense. I'm a big fan of open clean design with only lines or a simple animal or something that represents success or challenges like a trophy or gold medal. Ideally it would look good on a t-shirt, sticker, coin, etc. so would look good monochromatic and be simple and recognizable.

**Comment by zuurw** [comment]
Hi @danieluhl 
I create 3 designs for Friday Challenge, so I create 3 logos based on the letters F and C, the last one I read on your last post that I could use a simple animal for the logo, so I create a 
owl that is an animal that means wisdom and learning, in the head of the owl I created a checkmark as a reference to the tasks and challenges that we can do in the Friday Challenge.

See if you like one of this, If not I can moke other one or change something .

Cheers!

![logo](https://user-images.githubusercontent.com/40801473/58568274-e218ee00-822b-11e9-9077-77f7b59c12f5.jpg)

**Comment by danieluhl** [comment]
Wow, this is awesome, thanks so much for the work! I'm leaning towards the first one. @ssanchez @chrisjtraver What do you think?

**Comment by zuurw** [comment]
When you choose the one you like more, just tell me, to create the files to send to you.

Greetings!

**Comment by danieluhl** [comment]
@zuurw We're going with the first one. Thanks again for doing this, what's the best way to receive the files?

**Comment by zuurw** [comment]
Hi @danieluhl, give just one or two days to create the files and then I open a pull request.
Do you prefer other colors for the logo? I will create the black and white also, and the favicon as well.
Greetings

**Comment by zuurw** [comment]
Hi @danieluhl I send a pullrequest with the logo files and update the readme file.

See if everything is ok.

Greetings!

**Comment by danieluhl** [comment]
Merged, thanks so much for the great work, you're awesome! ⭐️

**Comment by chrisjtraver** [comment]
Thanks for your hard work on this @zuurw the new logo looks great! I'm going to close this issue.
